### ISSUE TITLE
Getting Nat onboarded

### ISSUE THREAD

**Issue by mike-hogan** [cozemble/breezbook#23]
- [x] migrate his tenant and configuration into the database
- [x] get push of basic data into airtable done
- [x] connect stripe webhooks to confirm order payment
- [x] connect his stripe account to his tenant
- [x] success page
- [x] cancellation flow
- [x] images for services
- [x] images for tenants
- [x] get locations into the model
- [x] #26
- [x] get thankYouUrl support into the app
- [x] endpoint to establish airtable refresh token (on per tenant-env basis)
- [x] Publish Nat's services and add-ons to his airtable
- [x] Investigate why service was not replicated to airtable, and make this robust
- [x] replicate cancellation events
- [x] fire airtable replication on booking, on payment, and on cancellation (wrapped endpoint?)
- [x] replicate booking cost into airtable
- [x] replicate booking add-ons into airtable.  Add-on ids can't have dots in them, so redo the mapping in x.sql

**Comment by Metehan-Altuntekin** [comment]
fastest solution for the payment redirect url seems to be adding a config field to the tenant settings and return it in the tenant get response. If it exists, the payment will redirect to it or default to the success page

**Comment by mike-hogan** [comment]
> fastest solution for the payment redirect url seems to be adding a config field to the tenant settings and return it in the tenant get response. If it exists, the payment will redirect to it or default to the success page

@Metehan-Altuntekin , I think Nat has different thank you pages for different services.  So the easiest might be to just look for a query param on the incoming booking url, and honour it if its present.

**Comment by Metehan-Altuntekin** [comment]
> > fastest solution for the payment redirect url seems to be adding a config field to the tenant settings and return it in the tenant get response. If it exists, the payment will redirect to it or default to the success page
> 
> @Metehan-Altuntekin , I think Nat has different thank you pages for different services. So the easiest might be to just look for a query param on the incoming booking url, and honour it if its present.

That makes sense for that case. Another solution may be allowing configuration for success return URL for each service but that is not going to allow customization from different redirects.

**Comment by Metehan-Altuntekin** [comment]
Implemented `success-return-url` via f38fd4b6e19b9133a8689e6acc89caedb588515b
